const recipearr: Array<any>=[
    {
        "Srno": 1,
        "RecipeName": "Masala Karela Recipe",
        "TranslatedRecipeName": "Masala Karela Recipe",
        "Ingredients": "6 Karela (Bitter Gourd/ Pavakkai) - deseeded,Salt - to taste,1 Onion - thinly sliced,3 tablespoon Gram flour (besan),2 teaspoons Turmeric powder (Haldi),1 tablespoon Red Chilli powder,2 teaspoons Cumin seeds (Jeera),1 tablespoon Coriander Powder (Dhania),1 tablespoon Amchur (Dry Mango Powder),Sunflower Oil - as required",
        "TranslatedIngredients": "6 Karela (Bitter Gourd/ Pavakkai) - deseeded,Salt - to taste,1 Onion - thinly sliced,3 tablespoon Gram flour (besan),2 teaspoons Turmeric powder (Haldi),1 tablespoon Red Chilli powder,2 teaspoons Cumin seeds (Jeera),1 tablespoon Coriander Powder (Dhania),1 tablespoon Amchur (Dry Mango Powder),Sunflower Oil - as required",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 45,
        "Servings": 6,
        "Cuisine": "Indian",
        "Course": "Side Dish",
        "Diet": "Diabetic Friendly",
        "Instructions": "To begin making the Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients. Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family. \r\n",
        "TranslatedInstructions": "To begin making the Masala Karela Recipe,de-seed the karela and slice. Do not remove the skin as the skin has all the nutrients. Add the karela to the pressure cooker with 3 tablespoon of water, salt and turmeric powder and pressure cook for three whistles. Release the pressure immediately and open the lids. Keep aside.Heat oil in a heavy bottomed pan or a kadhai. Add cumin seeds and let it sizzle.Once the cumin seeds have sizzled, add onions and saute them till it turns golden brown in color.Add the karela, red chilli powder, amchur powder, coriander powder and besan. Stir to combine the masalas into the karela.Drizzle a little extra oil on the top and mix again. Cover the pan and simmer Masala Karela stirring occasionally until everything comes together well. Turn off the heat.Transfer Masala Karela into a serving bowl and serve.Serve Masala Karela along with Panchmel Dal and Phulka for a weekday meal with your family. ",
        "URL": "https://www.archanaskitchen.com/masala-karela-recipe"
      },
      {
        "Srno": 2,
        "RecipeName": "टमाटर पुलियोगरे रेसिपी - Spicy Tomato Rice (Recipe In Hindi)",
        "TranslatedRecipeName": "Spicy Tomato Rice (Recipe)",
        "Ingredients": "2-1/2 कप चावल - पका ले,3 टमाटर,3 छोटा चमच्च बीसी बेले भात पाउडर,नमक - स्वाद अनुसार,1 छोटा चमच्च चना दाल,1/2 छोटा चमच्च जीरा,1 छोटा चमच्च सफ़ेद उरद दाल,1/2 छोटा चमच्च राइ,1 हरी मिर्च,1 सुखी लाल मिर्च,2 छोटा चमच्च काजू - या मूंगफली,1-1/2 बड़े चमच्च तेल - प्रयोग अनुसार,1/2 छोटा चमच्च हींग",
        "TranslatedIngredients": "2-1 / 2 cups rice - cooked, 3 tomatoes, 3 teaspoons BC Belle Bhat powder, salt - as per taste, 1 teaspoon chickpea lentils, 1/2 teaspoon cumin seeds, 1 teaspoon white urad dal, 1/2 Teaspoon mustard, 1 green chilli, 1 dry red chilli, 2 teaspoon cashew - or peanuts, 1-1 / 2 tablespoon oil - 1/2 teaspoon asafoetida",
        "PrepTimeInMins": 5,
        "CookTimeInMins": 10,
        "TotalTimeInMins": 15,
        "Servings": 3,
        "Cuisine": "South Indian Recipes",
        "Course": "Main Course",
        "Diet": "Vegetarian",
        "Instructions": "टमाटर पुलियोगरे बनाने के लिए सबसे पहले टमाटर को काट ले. अब एक मिक्सर ग्राइंडर में डाले और उसकी प्यूरी बना ले. अब एक कढ़ाई में तेल गरम करें। तेल के गरम होने के बाद इसमें चना दाल, उरद दाल, काजू डाले और 10 से 20 सेकण्ड्स तक पकने दे. 10 से 20 सेकण्ड्स के बाद इसमें जीरा, राइ, हरी मिर्च, सुखी लाल मिर्च और कढ़ी पत्ता डाले। 30 सेकण्ड्स बाद इसमें टमाटर की प्यूरी डाले और मिला ले. इसमें बीसी बेले भात पाउडर, नमक डाले और मिला ले. 7 से 8 मिनट के लिए पकने दे और फिर गैस बंद कर दे. इसे एक बाउल में निकाले, इसमें पके हुए चावल डाले और मिला ले. गरमा गरम परोसे। टमाटर पुलियोगरे को टमाटर ककड़ी रायता और पापड़ के साथ दिन के खाने के लिए परोसे।\r\n",
        "TranslatedInstructions": "To make tomato puliogere, first cut the tomatoes. Now put in a mixer grinder and puree it. Now heat oil in a pan. After the oil is hot, add chana dal, urad dal, cashew and let it cook for 10 to 20 seconds. After 10 to 20 seconds, add cumin seeds, mustard seeds, green chillies, dry red chillies and curry leaves. After 30 seconds, add tomato puree to it and mix. Add BC Belle Bhat powder, salt and mix it. Allow to cook for 7 to 8 minutes and then turn off the gas. Take it out in a bowl, add cooked rice and mix it. Serve hot. Serve tomato puliogre with tomato cucumber raita and papad for dinner.",
        "URL": "http://www.archanaskitchen.com/spicy-tomato-rice-recipe-in-hindi"
      },
      {
        "Srno": 3,
        "RecipeName": "Ragi Semiya Upma Recipe - Ragi Millet Vermicelli Breakfast",
        "TranslatedRecipeName": "Ragi Semiya Upma Recipe - Ragi Millet Vermicelli Breakfast",
        "Ingredients": "1-1/2 cups Rice Vermicelli Noodles (Thin),1 Onion - sliced,1/2 cup Carrots (Gajjar) - chopped,1/3 cup Green peas (Matar),2 Green Chillies,1/4 teaspoon Asafoetida (hing),1 teaspoon Mustard seeds,1 teaspoon White Urad Dal (Split),1 teaspoon Ghee,1 sprig Curry leaves,Salt - to taste,1 teaspoon Lemon juice",
        "TranslatedIngredients": "1-1/2 cups Rice Vermicelli Noodles (Thin),1 Onion - sliced,1/2 cup Carrots (Gajjar) - chopped,1/3 cup Green peas (Matar),2 Green Chillies,1/4 teaspoon Asafoetida (hing),1 teaspoon Mustard seeds,1 teaspoon White Urad Dal (Split),1 teaspoon Ghee,1 sprig Curry leaves,Salt - to taste,1 teaspoon Lemon juice",
        "PrepTimeInMins": 20,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 50,
        "Servings": 4,
        "Cuisine": "South Indian Recipes",
        "Course": "South Indian Breakfast",
        "Diet": "High Protein Vegetarian",
        "Instructions": "To begin making the Ragi Vermicelli Recipe, first steam the ragi vermicelli in a rice cooker or a steamer for about 5-6 minutes or till it is cooked but firm.Keep aside this aside till later use. You can add a few drops of oil and mix it so that they don't stick to each other.Place a kadai on the heat, add the ghee or oil to it and when warm add hing and allow it to sizzle for 30 seconds. Then follow it up with mustard seeds, urad dal and curry leaves, and allow them to crackle.Saute for 1 minute or so till the urad dal is slightly browned.Then, add onions and fry till translucent and soft.Next, add the green chillies along with par boiled carrots and peas. Sprinkle some salt and cook for 2-3 minutes or until the vegetables are semi cooked.Then, add the steamed ragi vermicelli toss it together so the vegetables are all well combined.Switch off the heat, take the vermicelli out into a serving dish and to with lemon juice. Mix well and serve along with Coconut Chutney and a hot cup of coffee or tea for a wholesome breakfast.\r\n",
        "TranslatedInstructions": "To begin making the Ragi Vermicelli Recipe, first steam the ragi vermicelli in a rice cooker or a steamer for about 5-6 minutes or till it is cooked but firm.Keep aside this aside till later use. You can add a few drops of oil and mix it so that they don't stick to each other.Place a kadai on the heat, add the ghee or oil to it and when warm add hing and allow it to sizzle for 30 seconds. Then follow it up with mustard seeds, urad dal and curry leaves, and allow them to crackle.Saute for 1 minute or so till the urad dal is slightly browned.Then, add onions and fry till translucent and soft.Next, add the green chillies along with par boiled carrots and peas. Sprinkle some salt and cook for 2-3 minutes or until the vegetables are semi cooked.Then, add the steamed ragi vermicelli toss it together so the vegetables are all well combined.Switch off the heat, take the vermicelli out into a serving dish and to with lemon juice. Mix well and serve along with Coconut Chutney and a hot cup of coffee or tea for a wholesome breakfast.",
        "URL": "http://www.archanaskitchen.com/ragi-vermicelli-semiya-recipe-healthy-finger-millet-semiya-breakfast"
      },
      {
        "Srno": 4,
        "RecipeName": "Gongura Chicken Curry Recipe - Andhra Style Gongura Chicken",
        "TranslatedRecipeName": "Gongura Chicken Curry Recipe - Andhra Style Gongura Chicken",
        "Ingredients": "500 grams Chicken,2 Onion - chopped,1 Tomato - chopped,4 Green Chillies - slit,1 inch Ginger - finely chopped,6 cloves Garlic - finely chopped,1/2 teaspoon Turmeric powder (Haldi),1 teaspoon Garam masala powder,2 tablespoon Sesame (Gingelly) Oil,Salt - to taste,1/4 teaspoon Methi Seeds (Fenugreek Seeds),1 tablespoon Coriander (Dhania) Seeds,4 Dry Red Chillies,1 teaspoon Fennel seeds (Saunf),1 teaspoon Sesame (Gingelly) Oil,4 cloves Garlic,2 cups Sorrel Leaves (Gongura) - picked and chopped,Salt - to taste",
        "TranslatedIngredients": "500 grams Chicken,2 Onion - chopped,1 Tomato - chopped,4 Green Chillies - slit,1 inch Ginger - finely chopped,6 cloves Garlic - finely chopped,1/2 teaspoon Turmeric powder (Haldi),1 teaspoon Garam masala powder,2 tablespoon Sesame (Gingelly) Oil,Salt - to taste,1/4 teaspoon Methi Seeds (Fenugreek Seeds),1 tablespoon Coriander (Dhania) Seeds,4 Dry Red Chillies,1 teaspoon Fennel seeds (Saunf),1 teaspoon Sesame (Gingelly) Oil,4 cloves Garlic,2 cups Sorrel Leaves (Gongura) - picked and chopped,Salt - to taste",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 45,
        "Servings": 4,
        "Cuisine": "Andhra",
        "Course": "Lunch",
        "Diet": "Non Vegeterian",
        "Instructions": "To begin making Gongura Chicken Curry Recipe first prep all the ingredients and keep them aside.In a small pan, dry roast the methi seeds, coriander seeds, fennel seeds and red chillies for about 3 to 4 minutes on medium heat, until you notice the seeds crackling. Once done, turn off the heat and allow it to cool a bit and blend it into a smooth powder.Heat oil in a pressure cooker over medium heat; add the chopped onions, ginger, garlic and green chillies and saute until the onions are lightly browned and tender.Add the tomatoes, and saute until the tomatoes become soft and mushy. Once done add the chicken, the garam masala and turmeric powder. Add 1/4 cup of water and pressure cook the chicken for 3 to 4 whistles and turn off the heat.Once done, allow the pressure to release naturally.Make sure there are no stems when you pick the gongura leaves. Wash and chop the gongura leaves and keep aside.In another pan,add some oil along garlic and saute the chopped gongura leaves along with a little salt and the ground masala. The gongura leaves will wilt almost instantly. Saute the gongura in the masala for about 3 to 4 minutes until it becomes like a mushy paste.Once done, add the cooked chicken curry into the Gongura masala and saute on high heat for another 2 minutes and turn off the heat.Check the salt and spices and adjust according to taste. Transfer the Gongura Chicken Curry to a serving bowl and serve hot.Serve Gongura Chicken with Ghee Rice Recipe | Neychoru , Tomato Onion Cucumber Raita Recipe and a Semiya Payasam for a delicious weekend lunch.\r\n",
        "TranslatedInstructions": "To begin making Gongura Chicken Curry Recipe first prep all the ingredients and keep them aside.In a small pan, dry roast the methi seeds, coriander seeds, fennel seeds and red chillies for about 3 to 4 minutes on medium heat, until you notice the seeds crackling. Once done, turn off the heat and allow it to cool a bit and blend it into a smooth powder.Heat oil in a pressure cooker over medium heat; add the chopped onions, ginger, garlic and green chillies and saute until the onions are lightly browned and tender.Add the tomatoes, and saute until the tomatoes become soft and mushy. Once done add the chicken, the garam masala and turmeric powder. Add 1/4 cup of water and pressure cook the chicken for 3 to 4 whistles and turn off the heat.Once done, allow the pressure to release naturally.Make sure there are no stems when you pick the gongura leaves. Wash and chop the gongura leaves and keep aside.In another pan,add some oil along garlic and saute the chopped gongura leaves along with a little salt and the ground masala. The gongura leaves will wilt almost instantly. Saute the gongura in the masala for about 3 to 4 minutes until it becomes like a mushy paste.Once done, add the cooked chicken curry into the Gongura masala and saute on high heat for another 2 minutes and turn off the heat.Check the salt and spices and adjust according to taste. Transfer the Gongura Chicken Curry to a serving bowl and serve hot.Serve Gongura Chicken with Ghee Rice Recipe | Neychoru , Tomato Onion Cucumber Raita Recipe and a Semiya Payasam for a delicious weekend lunch.",
        "URL": "http://www.archanaskitchen.com/gongura-chicken-curry-recipe-andhra-style-gongura-chicken"
      },
      {
        "Srno": 5,
        "RecipeName": "आंध्रा स्टाइल आलम पचड़ी रेसिपी - Adrak Chutney (Recipe In Hindi)",
        "TranslatedRecipeName": "Andhra Style Alam Pachadi Recipe - Adrak Chutney (Recipe)",
        "Ingredients": "1 बड़ा चमच्च चना दाल,1 बड़ा चमच्च सफ़ेद उरद दाल,2 सुखी लाल मिर्च,1 बड़ा चमच्च धनिये के बीज,3 इंच अदरक - काट ले,1 प्याज - काट ले,1 टमाटर - काट ले,नमक - स्वाद अनुसार,1 छोटा चमच्च राइ,हींग - चुटकी भर,तेल - प्रयोग अनुसार,1 टहनी कढ़ी",
        "TranslatedIngredients": "1 tablespoon chana dal, 1 tablespoon white urad dal, 2 red chillies, 1 tablespoon coriander seeds, 3 inches ginger - chop, 1 onion - chop, 1 tomato - chop, salt - as per taste, 1 Teaspoon mustard, asafoetida - a pinch, oil - as per use, 1 sprig curry",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 30,
        "Servings": 4,
        "Cuisine": "Andhra",
        "Course": "South Indian Breakfast",
        "Diet": "Vegetarian",
        "Instructions": "आंध्रा स्टाइल आलम पचड़ी बनाने के लिए सबसे पहले एक कढ़ाई में तेल गरम करे ले. इसमें दाल डाले और भूरा होने तक पका ले.अब इसमें सुखी लाल मिर्च, धनिये के बीज, प्याज, अदरक डाले और प्याज के नरम होने तक पकाए। प्याज के पकने के बाद, इसमें टमाटर डाले और टमाटर के नरम होने तक पका ले. गैस बंद करें और ठंडा होने दे. ठंडा होने के बाद इसको एक मिक्सर ग्राइंडर में डाले और पेस्ट बना ले.  तड़के के लिए, एक छोटी कढ़ाई में तेल गरम करें। इसमें राइ डाले और 10 सेकण्ड्स तक पकने दे. अब इसमें कढ़ी पत्ता, हींग डाले और 10 सेकण्ड्स तक पकने दे. इसे चटनी में डाले और मिला ले. आंध्रा स्टाइल आलम पचड़ी को घी रोस्ट डोसा और किरई सांबर के साथ सुबह के नाश्ते के लिए परोसे।\r\n",
        "TranslatedInstructions": "To make Andhra Style Alam Pachadi, first heat oil in a pan. Add lentils and cook till it turns brown. Now add dry red chillies, coriander seeds, onion, ginger and cook till the onion becomes soft. After the onion is cooked, add tomatoes and cook till the tomatoes become soft. Turn off the gas and allow it to cool. After it cools down, put it in a mixer grinder and make a paste. For tempering, heat the oil in a small pan. Add mustard seeds and let it cook for 10 seconds. Now add curry leaves, asafoetida and let it cook for 10 seconds. Add it to the chutney and mix. Serve Andhra Style Alam Pachadi with Ghee Roast Dosa and Kirai Sambar for breakfast.",
        "URL": "https://www.archanaskitchen.com/andhra-style-allam-pachadi-ginger-chutney-recipe-in-hindi"
      },
      {
        "Srno": 6,
        "RecipeName": "Pudina Khara Pongal Recipe (Rice and Lentils Cooked With Mint Leaves & Mild Spices)",
        "TranslatedRecipeName": "Pudina Khara Pongal Recipe (Rice and Lentils Cooked With Mint Leaves & Mild Spices)",
        "Ingredients": "1 cup Rice - soaked for 20 minutes,1/2 cup Yellow Moong Dal (Split) - soaked for 20 minutes,1 cup Mint Leaves (Pudina) - tightly packed,1/4 cup Coriander (Dhania) Leaves - tightly packed,1 Green Chilli,1 inch Ginger,1 teaspoon Cumin seeds (Jeera),5 cups Water,1 teaspoon Sunflower Oil,Salt - to taste,2 tablespoons Ghee,8 Cashew nuts - halved,1 teaspoon Cumin seeds (Jeera),1 teaspoon Whole Black Peppercorns,1 sprig Curry leaves,1 pinch Asafoetida (hing)",
        "TranslatedIngredients": "1 cup Rice - soaked for 20 minutes,1/2 cup Yellow Moong Dal (Split) - soaked for 20 minutes,1 cup Mint Leaves (Pudina) - tightly packed,1/4 cup Coriander (Dhania) Leaves - tightly packed,1 Green Chilli,1 inch Ginger,1 teaspoon Cumin seeds (Jeera),5 cups Water,1 teaspoon Sunflower Oil,Salt - to taste,2 tablespoons Ghee,8 Cashew nuts - halved,1 teaspoon Cumin seeds (Jeera),1 teaspoon Whole Black Peppercorns,1 sprig Curry leaves,1 pinch Asafoetida (hing)",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 30,
        "Servings": 4,
        "Cuisine": "South Indian Recipes",
        "Course": "South Indian Breakfast",
        "Diet": "High Protein Vegetarian",
        "Instructions": "To begin making Pudina Khara Pongal Recipe, wash and soak the rice and dal for 20 minutes.Make a paste of mint/pudina, coriander, green chilli and ginger using a mixer grinder and keep aside.Now, heat oil in the pressure cooker, add the cumin seeds and let it crackle.Add the soaked rice and dal and fry for a few minutes.Add the mint coriander paste and saute for a minute.Add 5 cups of water, season with salt and pressure cook for 4 to 5 whistles and keep aside.In the mean prepare the tadka by heating ghee in a small tadka pan.Add in the cumin seeds, peppercorns and let it crackle.Add the cashew halves and fry till they turn golden.Add the curry leaves and asafoetida and turn off the flame.Once the pressure has been released, open the lid and mash the pongal mixture.Add in the tadka over it and Serve the Pudina Khara Pongal Recipe along with Kathirikai Gothsu Recipe (Spicy and Tangy Eggplant Curry)and South Indian Coconut Chutney for a relaxed weekend breakfast.\r\n",
        "TranslatedInstructions": "To begin making Pudina Khara Pongal Recipe, wash and soak the rice and dal for 20 minutes.Make a paste of mint/pudina, coriander, green chilli and ginger using a mixer grinder and keep aside.Now, heat oil in the pressure cooker, add the cumin seeds and let it crackle.Add the soaked rice and dal and fry for a few minutes.Add the mint coriander paste and saute for a minute.Add 5 cups of water, season with salt and pressure cook for 4 to 5 whistles and keep aside.In the mean prepare the tadka by heating ghee in a small tadka pan.Add in the cumin seeds, peppercorns and let it crackle.Add the cashew halves and fry till they turn golden.Add the curry leaves and asafoetida and turn off the flame.Once the pressure has been released, open the lid and mash the pongal mixture.Add in the tadka over it and Serve the Pudina Khara Pongal Recipe along with Kathirikai Gothsu Recipe (Spicy and Tangy Eggplant Curry)and South Indian Coconut Chutney for a relaxed weekend breakfast.",
        "URL": "http://www.archanaskitchen.com/pudina-khara-pongal-recipe-rice-and-lentils-cooked-with-mint-leaves-mild-spices"
      },
      {
        "Srno": 7,
        "RecipeName": "Udupi Style Ash Gourd Coconut Curry Recipe",
        "TranslatedRecipeName": "Udupi Style Ash Gourd Coconut Curry Recipe",
        "Ingredients": "500 grams Vellai Poosanikai (Ash gourd/White Pumpkin),1/2 teaspoon Turmeric powder (Haldi),Salt - to taste,Sunflower Oil - for cooking,4 Dry Red Chillies,1/2 cup Fresh coconut - grated,30 grams Tamarind Water,1/2 teaspoon Methi Seeds (Fenugreek Seeds),1/2 teaspoon Cumin seeds (Jeera),2 teaspoons Coriander (Dhania) Seeds,2 teaspoons Sesame seeds (Til seeds),3 tablespoons Jaggery,1 cup Tamarind Water,1 teaspoon Sunflower Oil,1/2 teaspoon Mustard seeds,2 sprig Curry leaves - roughly torn,1 Dry Red Chillies",
        "TranslatedIngredients": "500 grams Vellai Poosanikai (Ash gourd/White Pumpkin),1/2 teaspoon Turmeric powder (Haldi),Salt - to taste,Sunflower Oil - for cooking,4 Dry Red Chillies,1/2 cup Fresh coconut - grated,30 grams Tamarind Water,1/2 teaspoon Methi Seeds (Fenugreek Seeds),1/2 teaspoon Cumin seeds (Jeera),2 teaspoons Coriander (Dhania) Seeds,2 teaspoons Sesame seeds (Til seeds),3 tablespoons Jaggery,1 cup Tamarind Water,1 teaspoon Sunflower Oil,1/2 teaspoon Mustard seeds,2 sprig Curry leaves - roughly torn,1 Dry Red Chillies",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 40,
        "Servings": 4,
        "Cuisine": "Udupi",
        "Course": "Lunch",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the Udupi Style Ash Gourd Coconut Curry Recipe  cook the ash gourd in the pressure cooker with little water, turmeric powder and salt for just 1 whistle. Release the pressure naturally.Soak the tamarind ball in hot water for about 15 minutes, and squeeze and keep the water.Then dry roast the spices and other ingredients for the ground paste in a pan except the coconut. Then grind it along with coconut to a smooth paste.In same pressure cooker which has the ash gourd add the paste and little water and give it stir. Keep the Udupi Ash Gourd Coconut Curry on the medium heat, Adjust the seasoning and texture if required. Once done transfer it in a bowl.For the seasoning, heat oil in a small skillet and add mustard seeds and let it crackle. After the mustard seeds have crackled add the curry leaves and red chillies. Tun off the heat after the red chillies have darkened and add it on top of the Udupi Style Ash Gourd Coconut Curry and serve. Serve the Udupi Style Ash Gourd Coconut Curry Recipe along with steamed rice, Elai Vadam  and Pisarna Manga for lunch.\r\n",
        "TranslatedInstructions": "To begin making the Udupi Style Ash Gourd Coconut Curry Recipe  cook the ash gourd in the pressure cooker with little water, turmeric powder and salt for just 1 whistle. Release the pressure naturally.Soak the tamarind ball in hot water for about 15 minutes, and squeeze and keep the water.Then dry roast the spices and other ingredients for the ground paste in a pan except the coconut. Then grind it along with coconut to a smooth paste.In same pressure cooker which has the ash gourd add the paste and little water and give it stir. Keep the Udupi Ash Gourd Coconut Curry on the medium heat, Adjust the seasoning and texture if required. Once done transfer it in a bowl.For the seasoning, heat oil in a small skillet and add mustard seeds and let it crackle. After the mustard seeds have crackled add the curry leaves and red chillies. Tun off the heat after the red chillies have darkened and add it on top of the Udupi Style Ash Gourd Coconut Curry and serve. Serve the Udupi Style Ash Gourd Coconut Curry Recipe along with steamed rice, Elai Vadam  and Pisarna Manga for lunch.",
        "URL": "http://www.archanaskitchen.com/udupi-style-ash-gourd-coconut-curry-recipe"
      },
      {
        "Srno": 8,
        "RecipeName": "Mexican Style Black Bean Burrito Recipe",
        "TranslatedRecipeName": "Mexican Style Black Bean Burrito Recipe",
        "Ingredients": "4 Tortillas,1/4 cup Black beans - soaked overnight and  cooked,6 to 8 Spinach Leaves (Palak),1 Onion - chopped,1 Tomato - chopped,2 cloves Garlic - chopped,2 sprig Coriander (Dhania) Leaves,1 cup Rice - or brown rice,1 Lemon juice,4 Spring Onion Greens - chopped,4 tablespoons Cheddar cheese,4 tablespoon Hung Curd (Greek Yogurt)",
        "TranslatedIngredients": "4 Tortillas,1/4 cup Black beans - soaked overnight and  cooked,6 to 8 Spinach Leaves (Palak),1 Onion - chopped,1 Tomato - chopped,2 cloves Garlic - chopped,2 sprig Coriander (Dhania) Leaves,1 cup Rice - or brown rice,1 Lemon juice,4 Spring Onion Greens - chopped,4 tablespoons Cheddar cheese,4 tablespoon Hung Curd (Greek Yogurt)",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 40,
        "Servings": 4,
        "Cuisine": "Mexican",
        "Course": "Lunch",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the Black Bean Burrito recipe, pick the coriander leaves and set aside, then finely slice the stalks.Keep it aside.Heat 1 tablespoon of oil in a heavy bottomed pan over a medium heat, add the chopped garlic and coriander stalks and fry till they become brown.Add the cooked beans, mix it well and cook for a minute. Add the rice and cook for further 5 minutes. Remove from the heat and add coriander leaves that were kept aside. For Salsa, toss together tomatoes, onions, spring onions, lime juice, coriander leaves, mix well using a fork and season to taste.Heat the tortillas on a griddle pan till it softens. Lay it on a plate.Layer spinach leaves over the  tortilla. Spoon one-quarter of the fried rice and beans, top with a generous spoonful of salsa.Grate over some cheese and add a spoon of yoghurt. Wrap up the burrito, then tuck it in.Repeat with the remaining ingredients to make the rest of the burritos. Serve Black Bean Burrito with a side of chips and a healthy Green Apple, Radish & Pepper Salad  and a glass of Carrot Pineapple Orange Juice Recipe to make a delicious lunch or dinner.\r\n",
        "TranslatedInstructions": "To begin making the Black Bean Burrito recipe, pick the coriander leaves and set aside, then finely slice the stalks.Keep it aside.Heat 1 tablespoon of oil in a heavy bottomed pan over a medium heat, add the chopped garlic and coriander stalks and fry till they become brown.Add the cooked beans, mix it well and cook for a minute. Add the rice and cook for further 5 minutes. Remove from the heat and add coriander leaves that were kept aside. For Salsa, toss together tomatoes, onions, spring onions, lime juice, coriander leaves, mix well using a fork and season to taste.Heat the tortillas on a griddle pan till it softens. Lay it on a plate.Layer spinach leaves over the  tortilla. Spoon one-quarter of the fried rice and beans, top with a generous spoonful of salsa.Grate over some cheese and add a spoon of yoghurt. Wrap up the burrito, then tuck it in.Repeat with the remaining ingredients to make the rest of the burritos. Serve Black Bean Burrito with a side of chips and a healthy Green Apple, Radish & Pepper Salad  and a glass of Carrot Pineapple Orange Juice Recipe to make a delicious lunch or dinner.",
        "URL": "https://www.archanaskitchen.com/black-bean-burrito-recipe"
      },
      {
        "Srno": 9,
        "RecipeName": "Spicy Crunchy Masala Idli Recipe",
        "TranslatedRecipeName": "Spicy Crunchy Masala Idli Recipe",
        "Ingredients": "10 Idli - cut into strips,1 cup Green Bell Pepper (Capsicum) - thinly sliced,1 cup Tomato - finely chopped,1 cup Onions - finely chopped,2 Green Chillies - finely chopped,1/4 teaspoon Red Chilli powder,1/2 teaspoon Turmeric powder (Haldi),3 tablespoons Tomato Ketchup,Coriander (Dhania) Leaves - to taste,Mint Leaves (Pudina) - to taste,2 teaspoons Sunflower Oil,Salt - to taste",
        "TranslatedIngredients": "10 Idli - cut into strips,1 cup Green Bell Pepper (Capsicum) - thinly sliced,1 cup Tomato - finely chopped,1 cup Onions - finely chopped,2 Green Chillies - finely chopped,1/4 teaspoon Red Chilli powder,1/2 teaspoon Turmeric powder (Haldi),3 tablespoons Tomato Ketchup,Coriander (Dhania) Leaves - to taste,Mint Leaves (Pudina) - to taste,2 teaspoons Sunflower Oil,Salt - to taste",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 30,
        "Servings": 3,
        "Cuisine": "South Indian Recipes",
        "Course": "Snack",
        "Diet": "Vegetarian",
        "Instructions": "To prepare Spicy Crunchy Masala Idli Recipe, Heat a tablespoon of oil in a heavy bottomed pan and stir fry them until they are lightly crisp. Transfer to a bowl and keep aside.In 2 teaspoons of oil the same pan; add in the onions, capsicum, green chillies and saute them on medium heat until tender. This takes about 5 to 7 minutes.  Add in the chopped tomatoes, salt, pepper, turmeric powder, chilli powder and stir well. Saute until the tomatoes turn soft. Finally stir in the tomato ketchup, the fried idli's the chopped coriander and mint leaves. Stir fry on high heat until well combined just for about a minute.Turn off the heat and transfer the Spicy Crunchy Masala Idli Recipe to a serving bowl and serve hot topped with more date chutney or tomato ketchup.\r\n",
        "TranslatedInstructions": "To prepare Spicy Crunchy Masala Idli Recipe, Heat a tablespoon of oil in a heavy bottomed pan and stir fry them until they are lightly crisp. Transfer to a bowl and keep aside.In 2 teaspoons of oil the same pan; add in the onions, capsicum, green chillies and saute them on medium heat until tender. This takes about 5 to 7 minutes.  Add in the chopped tomatoes, salt, pepper, turmeric powder, chilli powder and stir well. Saute until the tomatoes turn soft. Finally stir in the tomato ketchup, the fried idli's the chopped coriander and mint leaves. Stir fry on high heat until well combined just for about a minute.Turn off the heat and transfer the Spicy Crunchy Masala Idli Recipe to a serving bowl and serve hot topped with more date chutney or tomato ketchup.",
        "URL": "http://www.archanaskitchen.com/spicy-crunchy-masala-idli-recipe"
      },
      {
        "Srno": 10,
        "RecipeName": "गोभी के पत्तो की चटनी रेसिपी - Cauliflower Leaves Chutney (Recipe In Hindi)",
        "TranslatedRecipeName": "Cauliflower Leaves Chutney (Recipe in Hindi)",
        "Ingredients": "1 कप गोभी के पत्ते,3/4 कप टमाटर,18 ग्राम इमली,2 बड़े चमच्च सफ़ेद उरद दाल,4 सुखी लाल मिर्च,नमक - स्वाद अनुसार,हींग - चुटकी भर,3 कली लहसुन,हल्दी पाउडर - चुटकी भर,1 बड़ा चमच्च तेल,1 छोटा चमच्च राइ,1/2 छोटा चमच्च जीरा,1 टहनी कढ़ी पत्ता",
        "TranslatedIngredients": "1 cup cabbage leaves, 3/4 cup tomatoes, 18 grams tamarind, 2 tablespoons white urad dal, 4 red chillies, salt - as per taste, asafoetida - a pinch, 3 cloves garlic, turmeric powder - a pinch, 1 big Spoon oil, 1 teaspoon Rye, 1/2 teaspoon Cumin seeds, 1 sprig Curry leaves",
        "PrepTimeInMins": 5,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 25,
        "Servings": 3,
        "Cuisine": "South Indian Recipes",
        "Course": "Side Dish",
        "Diet": "Vegetarian",
        "Instructions": "गोभी के पत्तो की चटनी को बनाने के लिए सबसे पहले गोभी के अंदर की पत्तिया निकाले और अच्छी तरह से धो ले. सूखा ले और अच्छी तरह से काट ले.एक कढ़ाई में तेल गरम कर ले. इसमें उरद दाल, सुखी लाल मिर्च डाले और दाल के सुनहरा होने तक पकाए। अलग से रख दे. उसी कढ़ाई में थोड़ा और तेल डाले। इसमें गोभी के पत्ते, नमक डाले और पत्तो के नरम होने तक पकाए। अब इसमें टमाटर, लहसुन डाले और अच्छी तरह से मिला ले. टमाटर के नरम होने तक पकाए। पकने के बाद, गैस बंद करें और इस मिश्रण को ठंडा होने दे. इसे एक मिक्सर ग्राइंडर में दाल के मिश्रण के साथ डाले और पीस ले. थोड़ा पानी और नमक डाले और एक बार फिर से पीस ले.  तड़के के लिए, एक तड़का पैन में राइ डाले। 10 सेकण्ड्स बाद इसमें जीरा, हींग और कढ़ी पत्ता डाले। 15 सेकण्ड्स बाद इसे चटनी में डाले और मिला ले. गोभी के पत्तो की चटनी को वेजिटेबल सांबर और चावल के साथ दिन के खाने के लिए परोसे।\r\n",
        "TranslatedInstructions": "To make cauliflower leaf chutney, first of all take out the leaf inside the cabbage and wash it well. Dry and cut it well. Heat the oil in a pan. Add urad dal, dry red chilli and cook till the dal turns golden. Keep it aside. Add some more oil to the same pan. Add cabbage leaves, salt and cook till the leaves become soft. Now add tomatoes, garlic and mix well. Cook until tomatoes are soft. After cooking, turn off the gas and allow this mixture to cool. Pour it into a mixer grinder with the dal mixture and grind it. Add some water and salt and grind it once more. For tempering, add mustard seeds to a tempering pan. After 10 seconds, add cumin, asafoetida and curry leaves. After 15 seconds, add it to the chutney and mix. Serve Cabbage Leaves Chutney with Vegetable Sambar and Rice for dinner.",
        "URL": "http://www.archanaskitchen.com/cauliflower-leaves-chutney-recipe-in-hindi"
      },
      {
        "Srno": 11,
        "RecipeName": "Homemade Baked Beans Recipe (Wholesome & Healthy)",
        "TranslatedRecipeName": "Homemade Baked Beans Recipe (Wholesome & Healthy)",
        "Ingredients": "250 grams Dry beans - (such as cannellini or soya beans),1 teaspoon Extra Virgin Olive Oil,1 Onion - finely chopped,1 clove Garlic - grated,500 grams Tomatoes - pureed,1 tablespoon Honey - or more to taste,1 teaspoon Cumin powder (Jeera),1 teaspoon Dried oregano,1/4 teaspoon Red Chilli powder - or cayenne pepper,Salt and Pepper - (coarsely pounded pepper) to taste",
        "TranslatedIngredients": "250 grams Dry beans - (such as cannellini or soya beans),1 teaspoon Extra Virgin Olive Oil,1 Onion - finely chopped,1 clove Garlic - grated,500 grams Tomatoes - pureed,1 tablespoon Honey - or more to taste,1 teaspoon Cumin powder (Jeera),1 teaspoon Dried oregano,1/4 teaspoon Red Chilli powder - or cayenne pepper,Salt and Pepper - (coarsely pounded pepper) to taste",
        "PrepTimeInMins": 60,
        "CookTimeInMins": 60,
        "TotalTimeInMins": 120,
        "Servings": 4,
        "Cuisine": "Fusion",
        "Course": "High Protein Vegetarian",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the homemade baked beans recipe, we first have to soak the beans overnight for about 8 hours in water.We also have to make the cooked tomato puree. Click here to see the recipe of how to make tomato puree at home.Once the beans are soaked well, our next step is to cook them. I like using the pressure cooker method to cook the beans. Place the beans in the pressure, place the weight on, cover the pan and cook it along with 2-1/2 cups of water. After you heat 4 to 5 whistles, turn the heat to low and cook for another 15 minutes.Turn off the heat and allow the pressure cooker to release its pressure naturally. This would take another 10 minutes. The beans continue to cook under the pressure even when it is turned off.Once the pressure is released, open the cooker and drain out the excess liquids. You store this liquid and use it in the vegetable stock or risotto.Once the beans are cooked, our next step is to spice it up to make the baked beans.Heat oil in a sauce pan on medium heat; add in the onions and garlic and give it a light sauté until the onions are tender. Add the tomatoes, honey and the spices and give it a stir.Add in the cooked drained beans into the tomato gravy. Stir fry the beans until the beans get well coated with the tomatoes. Cover the pan, turn the heat to low and simmer the beans for about 30 minutes until you noticed the beans are well coated with the spices and tomatoes. Check the salt and seasoning levels and adjust to suit your taste.You can optionally garnish the Homemade Baked Beans with coriander leaves and serve it along with toast, or Potato Cakes Recipe.\r\n",
        "TranslatedInstructions": "To begin making the homemade baked beans recipe, we first have to soak the beans overnight for about 8 hours in water.We also have to make the cooked tomato puree. Click here to see the recipe of how to make tomato puree at home.Once the beans are soaked well, our next step is to cook them. I like using the pressure cooker method to cook the beans. Place the beans in the pressure, place the weight on, cover the pan and cook it along with 2-1/2 cups of water. After you heat 4 to 5 whistles, turn the heat to low and cook for another 15 minutes.Turn off the heat and allow the pressure cooker to release its pressure naturally. This would take another 10 minutes. The beans continue to cook under the pressure even when it is turned off.Once the pressure is released, open the cooker and drain out the excess liquids. You store this liquid and use it in the vegetable stock or risotto.Once the beans are cooked, our next step is to spice it up to make the baked beans.Heat oil in a sauce pan on medium heat; add in the onions and garlic and give it a light sauté until the onions are tender. Add the tomatoes, honey and the spices and give it a stir.Add in the cooked drained beans into the tomato gravy. Stir fry the beans until the beans get well coated with the tomatoes. Cover the pan, turn the heat to low and simmer the beans for about 30 minutes until you noticed the beans are well coated with the spices and tomatoes. Check the salt and seasoning levels and adjust to suit your taste.You can optionally garnish the Homemade Baked Beans with coriander leaves and serve it along with toast, or Potato Cakes Recipe.",
        "URL": "https://www.archanaskitchen.com/homemade-baked-beans-recipe-wholesome-healthy"
      },
      {
        "Srno": 12,
        "RecipeName": "Veg Chili Cheese Burgers Recipe",
        "TranslatedRecipeName": "Veg Chili Cheese Burgers Recipe",
        "Ingredients": "2 Burger buns,5 Pickled Jalapenos - sliced,2 Cheese Slices,2 Potatoes (Aloo) - pressure cooked,1 Onion - chopped,1 tablespoon Red Chilli powder,Salt - to taste,1 Whole Egg,1/2 cup Whole Wheat Bread crumbs,4 cloves Garlic - chopped,1 Onions - chopped,2 Tomatoes - chopped,1 cup Homemade tomato puree,1 Green Bell Pepper (Capsicum) - chopped,1/2 cup Soy granules,1 tablespoon Red Chilli powder,1 teaspoon Red Chilli flakes,1 tablespoon Cumin powder (Jeera),1 tablespoon Dried oregano,1 tablespoon Tabasco Original - Hot Sauce,1 teaspoon Honey,Salt - to taste,Sunflower Oil",
        "TranslatedIngredients": "2 Burger buns,5 Pickled Jalapenos - sliced,2 Cheese Slices,2 Potatoes (Aloo) - pressure cooked,1 Onion - chopped,1 tablespoon Red Chilli powder,Salt - to taste,1 Whole Egg,1/2 cup Whole Wheat Bread crumbs,4 cloves Garlic - chopped,1 Onions - chopped,2 Tomatoes - chopped,1 cup Homemade tomato puree,1 Green Bell Pepper (Capsicum) - chopped,1/2 cup Soy granules,1 tablespoon Red Chilli powder,1 teaspoon Red Chilli flakes,1 tablespoon Cumin powder (Jeera),1 tablespoon Dried oregano,1 tablespoon Tabasco Original - Hot Sauce,1 teaspoon Honey,Salt - to taste,Sunflower Oil",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 45,
        "TotalTimeInMins": 55,
        "Servings": 4,
        "Cuisine": "Continental",
        "Course": "Main Course",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the Veg Chili Cheese Burgers Recipe, we will first pressure cook the potatoes and keep it ready. Cook them for 5 whistles in a pressure cooker. Once done allow the pressure to release naturally and peel off the skin. Add them into a bowl and mash it using a potato masher.Add onions, salt and red chilli powder and bind it together. Shape them into medium sized cutlets and leave it in the fridge to rest until you move on to make the sauce.To make the sauce, heat a flat skillet with oil on medium heat, add garlic and allow it soften for few seconds.Add chopped onions and saute until they turn golden brown. Add chopped capsicum and saute for a few minutes. Add in chopped tomatoes and sprinkle with a bit of salt and saute till they turn mushy. Also add in the tomato puree and all the seasonings like, red chilli powder, cumin powder, red chilli flakes, dried oregano, tobacco sauce and honey.Keep sautéing until the tomatoes are cooked, you will notice the tomatoes will change color and the raw smell goes away.At the end add the soya granules and salt to taste. Add about 1/4 cup of water and allow it to boil for 4-6 minutes minutes. Let the sauce be little gravish.Switch off the heat, heat a flat skillet for the patties to shallow fry them. Take the patties out of the fridge. Beat an egg into a bowl and also keep the bread crumbs ready over a plate.Carefully dip the patties into the egg and place them over the bread crumbs and coat them well on either side Dust off the excess bread crumbs.Place the crumb dipped patties on to the hot skillet and drizzle some oil on top. Cook on either side for atleast 10 minutes. Till you can see brown color crispy layer on top.Do the same for the rest of the patties and set aside.Once done, add a tablespoon of butter on the same skillet and cut the burger bun in to half horizontally and toast them on the tawa. Toast till the burger buns are golden brown and crisp.Take a cooked patty, spoon two tablespoon of the sauce on top, place a cheese slice over it and microwave the patty for just 10 seconds until you see the cheese melt.Take the patty out, spread some of the sauce on the base of the burger bun and place the patty with cheese on top and add few slices of jalapeno and close it with the burger top and serve. Do the same for the rest of the burger.Serve the Veg Chili Cheese Burgers Recipe along with baby potato stir fry and Mango Iced Tea Recipe to make it a complete meal.\r\n",
        "TranslatedInstructions": "To begin making the Veg Chili Cheese Burgers Recipe, we will first pressure cook the potatoes and keep it ready. Cook them for 5 whistles in a pressure cooker. Once done allow the pressure to release naturally and peel off the skin. Add them into a bowl and mash it using a potato masher.Add onions, salt and red chilli powder and bind it together. Shape them into medium sized cutlets and leave it in the fridge to rest until you move on to make the sauce.To make the sauce, heat a flat skillet with oil on medium heat, add garlic and allow it soften for few seconds.Add chopped onions and saute until they turn golden brown. Add chopped capsicum and saute for a few minutes. Add in chopped tomatoes and sprinkle with a bit of salt and saute till they turn mushy. Also add in the tomato puree and all the seasonings like, red chilli powder, cumin powder, red chilli flakes, dried oregano, tobacco sauce and honey.Keep sautéing until the tomatoes are cooked, you will notice the tomatoes will change color and the raw smell goes away.At the end add the soya granules and salt to taste. Add about 1/4 cup of water and allow it to boil for 4-6 minutes minutes. Let the sauce be little gravish.Switch off the heat, heat a flat skillet for the patties to shallow fry them. Take the patties out of the fridge. Beat an egg into a bowl and also keep the bread crumbs ready over a plate.Carefully dip the patties into the egg and place them over the bread crumbs and coat them well on either side Dust off the excess bread crumbs.Place the crumb dipped patties on to the hot skillet and drizzle some oil on top. Cook on either side for atleast 10 minutes. Till you can see brown color crispy layer on top.Do the same for the rest of the patties and set aside.Once done, add a tablespoon of butter on the same skillet and cut the burger bun in to half horizontally and toast them on the tawa. Toast till the burger buns are golden brown and crisp.Take a cooked patty, spoon two tablespoon of the sauce on top, place a cheese slice over it and microwave the patty for just 10 seconds until you see the cheese melt.Take the patty out, spread some of the sauce on the base of the burger bun and place the patty with cheese on top and add few slices of jalapeno and close it with the burger top and serve. Do the same for the rest of the burger.Serve the Veg Chili Cheese Burgers Recipe along with baby potato stir fry and Mango Iced Tea Recipe to make it a complete meal.",
        "URL": "https://www.archanaskitchen.com/veg-chili-cheese-burgers-recipe"
      },
      {
        "Srno": 13,
        "RecipeName": "Andhra Style Ingavu Chaaru Recipe - Asafoetida Flavored Tamarind Rasam",
        "TranslatedRecipeName": "Andhra Steel Ingavu Charu Recipe - Asfoitida Flavored Tamarand Rasam",
        "Ingredients": "2 cup Tamarind Water,1/2 cup Arhar dal (Split Toor Dal),1 teaspoon Asafoetida (hing),Salt - to taste,1 teaspoon Mustard seeds,1 teaspoon Cumin seeds (Jeera),1 teaspoon Methi Seeds (Fenugreek Seeds),1 sprig Curry leaves,1 pinch Asafoetida (hing),Sunflower Oil - for cooking",
        "TranslatedIngredients": "2 cup Tamarind Water,1/2 cup Arhar dal (Split Toor Dal),1 teaspoon Asafoetida (hing),Salt - to taste,1 teaspoon Mustard seeds,1 teaspoon Cumin seeds (Jeera),1 teaspoon Methi Seeds (Fenugreek Seeds),1 sprig Curry leaves,1 pinch Asafoetida (hing),Sunflower Oil - for cooking",
        "PrepTimeInMins": 0,
        "CookTimeInMins": 30,
        "TotalTimeInMins": 30,
        "Servings": 4,
        "Cuisine": "Andhra",
        "Course": "Lunch",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the Andhra Style Ingavu Chaaru Recipe pressure cook the tamarind water with toor dal, hing and salt for about 4 whistles. Turn off the flame and allow the pressure to release naturally. Open the lif of the cooker and thoroughly mash the dal and bring the whole mixture together by mixing it well. To temper, heat a kadai with oil, add mustard seeds, cumin seeds, fenugreek seeds and allow it to crackle.Add curry leaves, pinch of hing and leave it for 2 seconds and pour it over the rasam. Serve the Andhra Style Ingavu Chaaru Recipe along with steamed rice and Gorikayi Palya Recipe  as a comforting meal during your week day.\r\n",
        "TranslatedInstructions": "To begin making the Andhra Style Ingavu Chaaru Recipe pressure cook the tamarind water with toor dal, hing and salt for about 4 whistles. Turn off the flame and allow the pressure to release naturally. Open the lif of the cooker and thoroughly mash the dal and bring the whole mixture together by mixing it well. To temper, heat a kadai with oil, add mustard seeds, cumin seeds, fenugreek seeds and allow it to crackle.Add curry leaves, pinch of hing and leave it for 2 seconds and pour it over the rasam. Serve the Andhra Style Ingavu Chaaru Recipe along with steamed rice and Gorikayi Palya Recipe  as a comforting meal during your week day.",
        "URL": "https://www.archanaskitchen.com/andhra-style-ingavu-chaaru-recipe-asafetida-flavored-tamarind-rasam"
      },
      {
        "Srno": 14,
        "RecipeName": "Aar Macher Jhol Recipe - Bengali Style Fish In Tomato Gravy",
        "TranslatedRecipeName": "And fish soup recipe - Bengali style fish in tomato gravy",
        "Ingredients": "600 grams Aar Maach (fish) - rohu/ katla fish (cut into thick steaks),1 Tomato - finely chopped,2 Bay leaves (tej patta),1-1/2 tablespoons Ginger - paste,4 Green Chillies - coarsely crushed,1 teaspoon Cumin powder (Jeera),1 teaspoon Coriander Powder (Dhania),Salt - to taste,1/2 teaspoon Cumin seeds (Jeera),1/2 teaspoon Turmeric powder (Haldi),2 Green Chillies - slit lengthwise,Mustard oil - as required,1-1/4 cups Water - add 2 cups if you like a loose gravy,Sugar - a pinch (optional),1 tablespoon Coriander (Dhania) Leaves - optional",
        "TranslatedIngredients": "600 grams Aar Maach (fish) - rohu/ katla fish (cut into thick steaks),1 Tomato - finely chopped,2 Bay leaves (tej patta),1-1/2 tablespoons Ginger - paste,4 Green Chillies - coarsely crushed,1 teaspoon Cumin powder (Jeera),1 teaspoon Coriander Powder (Dhania),Salt - to taste,1/2 teaspoon Cumin seeds (Jeera),1/2 teaspoon Turmeric powder (Haldi),2 Green Chillies - slit lengthwise,Mustard oil - as required,1-1/4 cups Water - add 2 cups if you like a loose gravy,Sugar - a pinch (optional),1 tablespoon Coriander (Dhania) Leaves - optional",
        "PrepTimeInMins": 5,
        "CookTimeInMins": 15,
        "TotalTimeInMins": 20,
        "Servings": 2,
        "Cuisine": "Bengali Recipes",
        "Course": "Dinner",
        "Diet": "High Protein Non Vegetarian",
        "Instructions": "To begin making the Aar Macher Jhol Recipe, firstly marinate the fish with salt and turmeric powder.Heat oil in a wok and shallow fry the fish on both sides till they turn crispy and golden. Remove and keep aside.Into the same wok, add bay leaves and cumin seeds. Fry these for 1 minute and add the chopped tomatoes.Sauté well. Into this Bengali Style Fish Gravy, add turmeric powder, cumin powder, coriander powder and enough salt and sauté till tomatoes soften. Add the ginger paste and coarsely crushed green chilies. Sauté till raw smell goes away and oil floats.Now add the water and allow the Fish gravy to come to a boil. Once the gravy starts boiling, add the fried fish and cook covered till fish has cooked through. [This should take about 6 to 8 minutes approximately]Once the fish has cooked through, add the slit green chilies, adjust salt if necessary and add sugar to taste. Allow it to cook for 5 minutes.Garnish this Bengali Fish Curry with coriander leaves and serve hot. Serve piping hot Aar Macher Jhol – Fish In Spicy Tomato Gravy along with Steamed Rice and Begun Bhaja for a weekday lunch or dinner. Enjoy!\r\n",
        "TranslatedInstructions": "To begin making the Aar Macher Jhol Recipe, firstly marinate the fish with salt and turmeric powder.Heat oil in a wok and shallow fry the fish on both sides till they turn crispy and golden. Remove and keep aside.Into the same wok, add bay leaves and cumin seeds. Fry these for 1 minute and add the chopped tomatoes.Sauté well. Into this Bengali Style Fish Gravy, add turmeric powder, cumin powder, coriander powder and enough salt and sauté till tomatoes soften. Add the ginger paste and coarsely crushed green chilies. Sauté till raw smell goes away and oil floats.Now add the water and allow the Fish gravy to come to a boil. Once the gravy starts boiling, add the fried fish and cook covered till fish has cooked through. [This should take about 6 to 8 minutes approximately]Once the fish has cooked through, add the slit green chilies, adjust salt if necessary and add sugar to taste. Allow it to cook for 5 minutes.Garnish this Bengali Fish Curry with coriander leaves and serve hot. Serve piping hot Aar Macher Jhol – Fish In Spicy Tomato Gravy along with Steamed Rice and Begun Bhaja for a weekday lunch or dinner. Enjoy!",
        "URL": "https://www.archanaskitchen.com/aar-macher-jhol-recipe-bengali-style-fish-in-spicy-tomato-gravy"
      },
      {
        "Srno": 15,
        "RecipeName": "Saunf Aloo (Fennel Potato Curry) Recipe",
        "TranslatedRecipeName": "Saunf Aloo (Fennel Potato Curry) Recipe",
        "Ingredients": "5 Potatoes (Aloo) - halved with skin,2 teaspoon Fennel seeds (Saunf) - crushed,2 teaspoon Red Chilli powder,1 teaspoon Turmeric powder (Haldi),1/4 cup Fresh cream - or 1/2 cup milk,4 sprig Coriander (Dhania) Leaves - finely chopped",
        "TranslatedIngredients": "5 Potatoes (Aloo) - halved with skin,2 teaspoon Fennel seeds (Saunf) - crushed,2 teaspoon Red Chilli powder,1 teaspoon Turmeric powder (Haldi),1/4 cup Fresh cream - or 1/2 cup milk,4 sprig Coriander (Dhania) Leaves - finely chopped",
        "PrepTimeInMins": 10,
        "CookTimeInMins": 15,
        "TotalTimeInMins": 25,
        "Servings": 6,
        "Cuisine": "Punjabi",
        "Course": "Lunch",
        "Diet": "Vegetarian",
        "Instructions": "To begin with Saunf Aloo, heat oil in a pressure cooker. Add turmeric powder, salt, red chilli powder and crushed fennel seeds till the fennel seeds turns golden in colour.Now add the potatoes and mix it properly with the masala. Sauce it for 2-3 minutes and then add enough water to cover the potatoes in the cooker.Switch the heat after two whistles and once the pressure is released, open the lid of the pressure cooker.The next step is to add the cream or milk and mash a few potatoes to get a thicker consistency. Let it cook for 5 more minutes or until the cooker releases 2 more whistles.Garnish the Saunf Aloo with some roasted saunf and chopped coriander. Serve Sauf Aloo along with Amritsari Dal and Whole Wheat lachha Paratha for a weekday meal.\r\n",
        "TranslatedInstructions": "To begin with Saunf Aloo, heat oil in a pressure cooker. Add turmeric powder, salt, red chilli powder and crushed fennel seeds till the fennel seeds turns golden in colour.Now add the potatoes and mix it properly with the masala. Sauce it for 2-3 minutes and then add enough water to cover the potatoes in the cooker.Switch the heat after two whistles and once the pressure is released, open the lid of the pressure cooker.The next step is to add the cream or milk and mash a few potatoes to get a thicker consistency. Let it cook for 5 more minutes or until the cooker releases 2 more whistles.Garnish the Saunf Aloo with some roasted saunf and chopped coriander. Serve Sauf Aloo along with Amritsari Dal and Whole Wheat lachha Paratha for a weekday meal.",
        "URL": "https://www.archanaskitchen.com/saunf-aloo-fennel-potato-curry-recipe"
      },
      {
        "Srno": 16,
        "RecipeName": "साउथ इंडियन प्याज चटनी रेसिपी - South Indian Onion Chutney (Recipe In Hindi)",
        "TranslatedRecipeName": "South Indian Onion Chutney Recipe - South Indian Onion Chutney (Recipe)",
        "Ingredients": "2 प्याज,1 छोटा चमच्च जीरा,2 बड़े चमच्च काली उरद दाल (स्प्लिट),1 बड़ा चमच्च इमली का पेस्ट,3 सुखी लाल मिर्च,1/2 छोटा चमच्च गुड़,2 छोटे चमच्च तेल,नमक - स्वाद अनुसार,1 छोटा चमच्च राइ,1 टहनी कढ़ी पत्ता,1/2 छोटा चमच्च तेल",
        "TranslatedIngredients": "2 onions, 1 teaspoon cumin seeds, 2 tablespoons black urad dal (split), 1 tablespoon tamarind paste, 3 dry red chillies, 1/2 teaspoon jaggery, 2 teaspoons oil, salt - 1 teaspoon, as per taste Rye, 1 sprig curry leaves, 1/2 teaspoon oil",
        "PrepTimeInMins": 20,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 40,
        "Servings": 4,
        "Cuisine": "South Indian Recipes",
        "Course": "Side Dish",
        "Diet": "Vegetarian",
        "Instructions": "साउथ इंडियन प्याज चटनी बनाने के लिए सब पहले प्याज को काट ले और अलग से रख दे. अब 1 छोटा चमच्च तेल कढ़ाई में गरम करें। इसमें जीरा, सुखी लाल मिर्च डाले और 10 सेकण्ड्स के लिए पकने दे.अब इसमें उरद दाल डाले और सुनहरा होने तक पकने दे. गैस बंद करें और एक बाउल में निकाल दे. उसी कड़ाही में एक चमच्च तेल और डाले। इसमें प्याज डाले और 4 से 5 मिनट तक पकने दे. गैस बंद करें और ठंडा होने दे.अब उरद दाल, जीरा और सुखी लाल मिर्च को मिक्सर ग्राइंडर में डाले और पीस ले. इसमें पके हुए प्याज, इमली और गुड़ डाले। थोड़ा पानी डाले और पीस ले. अब तड़के के लिए, एक छोटी कढ़ाई में तेल गरम करें। इसमें राइ और कढ़ी पत्ता डाले। 10 सेकण्ड्स बाद इसे चटनी में डाले और मिला ले. साउथ इंडियन प्याज की चटनी को मसाला डोसा या घी डोसा के साथ सुनाग के नाश्ते के लिए परोसे।\r\n",
        "TranslatedInstructions": "To make South Indian Onion Chutney, first of all chop the onion and keep it aside. Now heat 1 teaspoon of oil in the pan. Add cumin seeds, dry red chillies and let it cook for 10 seconds. Now add urad dal in it and let it cook till it becomes golden. Turn off the gas and drain in a bowl. Add another spoon of oil to the same pan. Add onions and let it cook for 4 to 5 minutes. Turn off the gas and let it cool down. Now put urad dal, cumin and dry red chillies in the mixer grinder and grind them. Add cooked onions, tamarind and jaggery. Add some water and grind it. Now for the tempering, heat the oil in a small pan. Add mustard seeds and curry leaves. After 10 seconds, add it to the chutney and mix. Serve South Indian onion chutney with masala dosa or ghee dosa for a tsunag breakfast.",
        "URL": "http://www.archanaskitchen.com/south-indian-onion-chutney-recipe-in-hindi"
      },
      {
        "Srno": 17,
        "RecipeName": "Hariyali Egg Curry Recipe In Coriander and Mint Gravy",
        "TranslatedRecipeName": "Hariyali Egg Curry Recipe In Coriander and Mint Gravy",
        "Ingredients": "4 Whole Eggs - boiled,1 Cinnamon Stick (Dalchini) - small,1 Bay leaf (tej patta),2 Cloves (Laung),1 tablespoon Sunflower Oil,2 teaspoons Coriander Powder (Dhania),1 teaspoon Garam masala powder,2 tablespoons Fresh cream,2 cups Coriander (Dhania) Leaves - tightly packed,1 cup Mint Leaves (Pudina) - chopped,2 Green Chillies - chopped,1 Onion - roughly chopped,1 inch Ginger - chopped,4 cloves Garlic",
        "TranslatedIngredients": "4 Whole Eggs - boiled,1 Cinnamon Stick (Dalchini) - small,1 Bay leaf (tej patta),2 Cloves (Laung),1 tablespoon Sunflower Oil,2 teaspoons Coriander Powder (Dhania),1 teaspoon Garam masala powder,2 tablespoons Fresh cream,2 cups Coriander (Dhania) Leaves - tightly packed,1 cup Mint Leaves (Pudina) - chopped,2 Green Chillies - chopped,1 Onion - roughly chopped,1 inch Ginger - chopped,4 cloves Garlic",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 20,
        "TotalTimeInMins": 35,
        "Servings": 4,
        "Cuisine": "Indian",
        "Course": "Lunch",
        "Diet": "Eggetarian",
        "Instructions": "To begin making the Hariyali Egg Curry recipe, we will first make the Hariyali Masala.Into the Mixer Grinder (medium jar), add the Coriander leaves mint leaves, Green Chillies and 1/2 cup water. Blend all of them together to make a smooth paste and keep aside.Into the small jar of the mixer grinder, add the onions, ginger and garlic and grind to make a paste. Heat 1 tablespoon oil in a kadai over medium heat, add the Bay leaf (tej patta), Cloves, Cinnamon Stick and roast for a few seconds. Add the Onion ginger garlic paste.Saute for 4 to 5 minutes until raw onion smell goes away.Once the onions are roasted, add garam masala powder, coriander powder and saute for a few seconds.Add the Hariyali Coriander Mint Mixture, the fresh cream and the 4 Boiled eggs.Add water if required to adjust the consistency of the Hariyali Egg Curry.  Cover & simmer the Hariyali Egg Curry for 5 minutes.Check the salt and spices and adjust to according to your taste and transfer the Hariyali Egg Curry into a serving bowl. Serve the Hariyali Egg Curry along with Malabar Parotta or  Whole Wheat Lachha Paratha and Burani Raita for a weeknight dinner.\r\n",
        "TranslatedInstructions": "To begin making the Hariyali Egg Curry recipe, we will first make the Hariyali Masala.Into the Mixer Grinder (medium jar), add the Coriander leaves mint leaves, Green Chillies and 1/2 cup water. Blend all of them together to make a smooth paste and keep aside.Into the small jar of the mixer grinder, add the onions, ginger and garlic and grind to make a paste. Heat 1 tablespoon oil in a kadai over medium heat, add the Bay leaf (tej patta), Cloves, Cinnamon Stick and roast for a few seconds. Add the Onion ginger garlic paste.Saute for 4 to 5 minutes until raw onion smell goes away.Once the onions are roasted, add garam masala powder, coriander powder and saute for a few seconds.Add the Hariyali Coriander Mint Mixture, the fresh cream and the 4 Boiled eggs.Add water if required to adjust the consistency of the Hariyali Egg Curry.  Cover & simmer the Hariyali Egg Curry for 5 minutes.Check the salt and spices and adjust to according to your taste and transfer the Hariyali Egg Curry into a serving bowl. Serve the Hariyali Egg Curry along with Malabar Parotta or  Whole Wheat Lachha Paratha and Burani Raita for a weeknight dinner.",
        "URL": "https://www.archanaskitchen.com/hariyali-egg-curry-recipe-in-coriander-and-mint-gravy"
      },
      {
        "Srno": 18,
        "RecipeName": "लौकी रायता रेसिपी - Grated Bottle Gourd Yogurt Salad (Recipe In Hindi)",
        "TranslatedRecipeName": "Gourd Raita Recipe - Grated Bottle Gourd Yogurt Salad",
        "Ingredients": "2 कप दही,1 कप लौकी - छीलकर कस ले,1 ककड़ी - छीलकर कास ले,1 हरी - बारीक काट ले,1 हरा धनिया - थोड़ा,1/2 छोटा चमच्च जीरा पाउडर,नमक - स्वाद अनुसार",
        "TranslatedIngredients": "2 cups curd, 1 cup gourd - peel and tighten, 1 cucumber - peel and grind, 1 green - finely chopped, 1 green coriander - little, 1/2 teaspoon cumin powder, salt - as per taste",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 15,
        "TotalTimeInMins": 30,
        "Servings": 4,
        "Cuisine": "Indian",
        "Course": "Side Dish",
        "Diet": "Vegetarian",
        "Instructions": "लौकी रायता बनाने के लिए सब्ज़े पहले सारी सामग्री तैयार कर ले.एक बड़े बाउल में कसी हुई लौकी, ककड़ी, दही, हरी मिर्च, नमक, जीरा पाउडर और धनिया डाले। सबको अच्छी तरह से मिला ले और आपका रायता तैयार है. लौकी रायता को लहसुनि दाल, लौकी बड़ी की सब्ज़ी और फुल्के के साथ दिन के खाने के लिए परोसे।\r\n",
        "TranslatedInstructions": "To prepare gourd raita, prepare all the ingredients first. Add grated gourd, cucumber, curd, green chillies, salt, cumin powder and coriander in a large bowl. Mix well and your raita is ready. Serve gourd raita with Garlic Dal, gourd elder greens and phulka for dinner.",
        "URL": "http://www.archanaskitchen.com/grated-bottle-gourd-yogurt-salad-recipe-in-hindi"
      },
      {
        "Srno": 19,
        "RecipeName": "Homemade Tater Tots Recipe",
        "TranslatedRecipeName": "Homemade Tater Tots Recipe",
        "Ingredients": "10 Potatoes (Aloo),1 teaspoon Garlic powder,1 teaspoon Onion powder,1 teaspoon Dried oregano,1 tablespoon Coriander (Dhania) Leaves - finely chopped,1 teaspoon Red Chilli flakes,2 tablespoon All Purpose Flour (Maida),1 tablespoon Rice flour,Salt - to taste,Sunflower Oil - for deep frying the tater tots",
        "TranslatedIngredients": "10 Potatoes (Aloo),1 teaspoon Garlic powder,1 teaspoon Onion powder,1 teaspoon Dried oregano,1 tablespoon Coriander (Dhania) Leaves - finely chopped,1 teaspoon Red Chilli flakes,2 tablespoon All Purpose Flour (Maida),1 tablespoon Rice flour,Salt - to taste,Sunflower Oil - for deep frying the tater tots",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 45,
        "TotalTimeInMins": 60,
        "Servings": 8,
        "Cuisine": "Continental",
        "Course": "Appetizer",
        "Diet": "Vegetarian",
        "Instructions": "To begin making the Homemade Tater Tots Recipe, scrub potatoes thoroughly and wash them until clean. Peel the skin of the potatoes and we will not parboil the potatoes in hot water. In a large saucepan, add the potatoes and boil it brisk for about 5 to 7 minutes. After 5 to 7 minutes the potatoes would have boiled through slightly, but firm.Once boiled, water the potatoes until cold water and pat dry. This process will cool the potatoes a little. Once slightly cooled, grate the potatoes into a large mixing bowl. Add the garlic powder, onion powder, dried oregano, red chili flakes, fresh coriander leaves, salt to taste, all purpose flour, rice flour and mix well to form a dough like consistency.The next step is to shape the potatoes and deep fry the tater tots. Grease your fingers and palm with oil and shape the potatoes into bite size ovals (cylinders).Heat oil in a pan for deep frying over medium heat. Carefully drop each one of the shaped Tater Tots in oil and fry them on medium heat until golden brown on all sides.Once done, remove the Tater Tots from the oil and place it on kitchen paper towels to absorb the excess oil.Serve the Tater Tots with tomato ketchup or a Sichuan Style Bird Eye Chili Sauce as a tea time snack or as an appetizer for parties.\r\n",
        "TranslatedInstructions": "To begin making the Homemade Tater Tots Recipe, scrub potatoes thoroughly and wash them until clean. Peel the skin of the potatoes and we will not parboil the potatoes in hot water. In a large saucepan, add the potatoes and boil it brisk for about 5 to 7 minutes. After 5 to 7 minutes the potatoes would have boiled through slightly, but firm.Once boiled, water the potatoes until cold water and pat dry. This process will cool the potatoes a little. Once slightly cooled, grate the potatoes into a large mixing bowl. Add the garlic powder, onion powder, dried oregano, red chili flakes, fresh coriander leaves, salt to taste, all purpose flour, rice flour and mix well to form a dough like consistency.The next step is to shape the potatoes and deep fry the tater tots. Grease your fingers and palm with oil and shape the potatoes into bite size ovals (cylinders).Heat oil in a pan for deep frying over medium heat. Carefully drop each one of the shaped Tater Tots in oil and fry them on medium heat until golden brown on all sides.Once done, remove the Tater Tots from the oil and place it on kitchen paper towels to absorb the excess oil.Serve the Tater Tots with tomato ketchup or a Sichuan Style Bird Eye Chili Sauce as a tea time snack or as an appetizer for parties.",
        "URL": "http://www.archanaskitchen.com/homemade-tater-tots-recipe"
      },
      {
        "Srno": 20,
        "RecipeName": "चेट्टिनाड वेजिटेबल पुलाव रेसिपी - Chettinad Vegetable Pulao Recipe",
        "TranslatedRecipeName": "Chettinad Vegetable Casserole Recipe - Chettinad Vegetable Pulao Recipe",
        "Ingredients": "1 कप चावल - पानी में अच्छी तरह से धो ले,12 छोटे प्याज - बारीक काट ले,2 कली लहसुन - कस ले,1 इंच अदरक - कस ले,2 हरी मिर्च - सीधा और पतला काट ले,1 तेज पत्ता - तोड़ ले,1 छोटा चम्मच लाल मिर्च पाउडर,1 छोटा चम्मच हल्दी पाउडर,1 गाजर - काट ले,12 हरा बीन्स - काट ले,2 आलू - छीलकर काट ले,घी - प्रयोग अनुसार,2 लौंग,1 इंच दालचीनी,1 छोटा चम्मच सौंफ,1 छोटा चम्मच पूरी काली मिर्च,1 छोटा चम्मच धनिया के बीज,1/4 कप हरे मटर - भाप ले,1/4 कप पुदीना - बारीक काट ले",
        "TranslatedIngredients": "1 cup rice - wash well in water, 12 small onions - finely chopped, 2 cloves garlic - tighten, 1 inch ginger - tighten, 2 green chillies - straight and thin cut, 1 bay leaf - break , 1 tsp red chilli powder, 1 tsp turmeric powder, 1 carrot - chop, 12 green beans - chop, 2 potatoes - peel and chop, ghee - as per use, 2 cloves, 1 inch cinnamon, 1 tsp fennel , 1 tsp whole pepper, 1 tsp coriander seeds, 1/4 cup green peas - steam, 1/4 cup mint leaves - finely chopped",
        "PrepTimeInMins": 15,
        "CookTimeInMins": 45,
        "TotalTimeInMins": 60,
        "Servings": 4,
        "Cuisine": "Chettinad",
        "Course": "Dinner",
        "Diet": "Vegetarian",
        "Instructions": "चेट्टिनाड वेजिटेबल पुलाव बनाने के लिए सबसे पहले सारी सब्जिआ काट ले. चावल को 30 मिनट के लिए भिगो दे. एक कढ़ाई को गैस पर गरम करें। इसमें लॉन्ग, दालचीनी, सौंफ, पूरी काली मिर्च, धनिया के बीज डाले सुर 2 से 3 मिनट के लिए सेक ले.  गैस बंद करें और इस मसाले के मिश्रण को ठंडा होने दे. ठंडा होने के बाद इसे एक ब्लेंडर में डाले और पीस ले. अलग से रख दे. अब एक कढ़ाई में घी गरम करें। इसमें अदरक, लहसुन, प्याज, हरी मिर्च डाले और प्याज के नरम होने तक पका ले. प्याज के नरम होने के बाद इसमें गाजर, हरा बीन्स, आलू, तेज पत्ता, हल्दी पाउडर, लाल मिर्च पाउडर, पिसा हुआ मसाला डाले और अच्छी तरह से मिला ले. 2 मिनट के बाद इसमें चावल, नमक, 2 कप पानी डाले और उबलने दे. उबाला आने के बाद, आंच कम करें, कढ़ाई को ढके और चावल के पक जाने तक पकाए। अगर चावल कच्चे रह जाए तो थोड़ा और पानी डालकर पका ले. पकने के बाद, गैस बंद करें, ढके और 10 मिनट के लिए लग से रख दे. परोसे। चेट्टिनाड वेजिटेबल पुलाव रेसिपी को बूंदी रायता और सेके हुए पापड़ के साथ दिन के खाने के लिए परोसे।\r\n",
        "TranslatedInstructions": "To make Chettinad vegetable casserole, first cut all the vegetables. Soak rice for 30 minutes. Heat a pan on gas. Add long, cinnamon, fennel, whole black pepper, coriander seeds, and roast for 2 to 3 minutes. Turn off the gas and allow this spice mixture to cool. After it cools down, put it in a blender and grind it. Keep it aside. Now heat ghee in a pan. Add ginger, garlic, onion, green chilies and cook till the onion becomes soft. After the onion becomes soft, add carrots, green beans, potatoes, bay leaves, turmeric powder, red chilli powder, ground spices and mix well. After 2 minutes, add rice, salt, 2 cups of water and let it boil. After boiling, reduce the heat, cover the pan and cook until the rice is cooked. If the rice remains raw, then add some more water and cook it. After cooking, turn off the gas, cover and keep it aside for 10 minutes. Serve. Serve Chettinad Vegetable Casserole Recipe along with Bundi Raita and Baked Papad for dinner.",
        "URL": "https://www.archanaskitchen.com/chettinad-vegetable-pulao-recipe-with-kohinoor-silver-basmati-rice-in-hindi"
      }
]